riffxtract - block type decode to use full 0-255 character range
On my system some test files crash at line 242 with errors like this:

```
Traceback (most recent call last):
  File "../riffxtract", line 347, in <module>
    parse_riff(fileContent, rifx_offset)
  File "../riffxtract", line 242, in parse_riff
    if (block_type[c].decode('ascii') > '\0' and
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```

Python's "ascii" supports only chars in range 0-127.  Using "latin1" codepage it can support the full 0-255 byte range.  Since these upper chars are replaced with `_` anyway, the fix seems OK to me.